apiVersion: v1
kind: Service
metadata: 
 name: service-${service.name}
 labels:
   app: ${service.name}
spec:
 type: LoadBalancer
 ports:
  - port: ${service.port}
    protocol: TCP
    targetPort: 8080
 selector:
  app: ${service.name}
